#location-video-path: C:/Users/Yan/Desktop/coc/user/avatar/
#47.113.229.216
#yan
#Cc$266233
server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coc?serverTimezone=Asia/Shanghai
    username: root
    password: 2662334834
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      jedis:
        pool:
          # 最大连接时长
          max-active: 10
          # 最大等待时长
          max-wait: 3000
          # 最大连接数
          max-idle: 8
          # 最小连接数
          min-idle: 2
      # 超时
      connect-timeout: 5000
#  web:
#    resources:
#      static-locations: classpath:/static/
mybatis-plus:
  #mapper??
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    # 开启小驼峰自动映射
    map-underscore-to-camel-case: true
    # 日志实现类
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted #逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
mybatis-plus-join:
  banner: false
logging:
  #日志配置
  config: classpath:logback-spring.xml
#  file:
#    name: CMS-%d{yyyy-MM-dd}.log
#    path: src/main/resources/log
#  level:
#    sql: debug
#    root: info

user:
  password:
    # 最大重试次数
    maxRetryCount: 5
    # 锁定市场
    lockTime: 10

coc:
  security:
    white-urls: ["/coc/user/login","/coc/user/register"]